dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

branches:
  only:
  - master

sources:
  - google-chrome
packages:
  - google-chrome-stable
  - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install


script:
  - npm run lint
  - npm run test-once
  - npm run e2e
